package io.github.therealmone.fireres.excel.style.chart;

import org.apache.poi.xddf.usermodel.PresetColor;

import static io.github.therealmone.fireres.core.utils.RandomUtils.generateValueInInterval;
import static org.apache.poi.xddf.usermodel.PresetColor.*;

public final class AvailableColors {

    private static final PresetColor[] COLORS = new PresetColor[] {
            AQUA,
            AQUAMARINE,
            BISQUE,
            BLACK,
            BLUE,
            BLUE_VIOLET,
            CADET_BLUE,
            CHARTREUSE,
            CHOCOLATE,
            CORAL,
            CORNFLOWER_BLUE,
            CRIMSON,
            CYAN,
            DEEP_PINK,
            DEEP_SKY_BLUE,
            DIM_GRAY,
            DARK_BLUE,
            DARK_CYAN,
            DARK_GOLDENROD,
            DARK_GRAY,
            DARK_GREEN,
            DARK_KHAKI,
            DARK_MAGENTA,
            DARK_OLIVE_GREEN,
            DARK_ORANGE,
            DARK_ORCHID,
            DARK_RED,
            DARK_SALMON,
            DARK_SEA_GREEN,
            DARK_SLATE_BLUE,
            DARK_SLATE_GRAY,
            DARK_TURQUOISE,
            DARK_VIOLET,
            DODGER_BLUE,
            FIREBRICK,
            FOREST_GREEN,
            FUCHSIA,
            GOLD,
            GOLDENROD,
            GRAY,
            GREEN,
            GREEN_YELLOW,
            HOT_PINK,
            INDIAN_RED,
            INDIGO,
            KHAKI,
            LAVENDER,
            LAWN_GREEN,
            LIME,
            LIME_GREEN,
            LIGHT_BLUE,
            LIGHT_CORAL,
            LIGHT_GRAY,
            LIGHT_GREEN,
            LIGHT_PINK,
            LIGHT_SALMON,
            LIGHT_SEA_GREEN,
            LIGHT_SKY_BLUE,
            LIGHT_SLATE_GRAY,
            LIGHT_STEEL_BLUE,
            MAGENTA,
            MAROON,
            MEDIUM_AQUAMARINE,
            MEDIUM_BLUE,
            MEDIUM_ORCHID,
            MEDIUM_PURPLE,
            MEDIUM_SEA_GREEN,
            MEDIUM_SLATE_BLUE,
            MEDIUM_SPRING_GREEN,
            MEDIUM_TURQUOISE,
            MEDIUM_VIOLET_RED,
            MIDNIGHT_BLUE,
            MOCCASIN,
            NAVY,
            OLIVE,
            OLIVE_DRAB,
            ORANGE,
            ORANGE_RED,
            ORCHID,
            PALE_GREEN,
            PALE_TURQUOISE,
            PALE_VIOLET_RED,
            PEACH_PUFF,
            PERU,
            PINK,
            PLUM,
            POWDER_BLUE,
            PURPLE,
            RED,
            ROSY_BROWN,
            ROYAL_BLUE,
            SADDLE_BROWN,
            SALMON,
            SANDY_BROWN,
            SEA_GREEN,
            SIENNA,
            SILVER,
            SKY_BLUE,
            SLATE_BLUE,
            SLATE_GRAY,
            SPRING_GREEN,
            STEEL_BLUE,
            TAN,
            TEAL,
            THISTLE,
            TOMATO,
            TURQUOISE,
            VIOLET,
            WHEAT,
            YELLOW,
            YELLOW_GREEN
    };

    public static PresetColor get() {
        return COLORS[generateValueInInterval(0, COLORS.length - 1)];
    }

}
